### ISSUE TITLE
Gather information about needed frameworks

### ISSUE THREAD

**Issue by DustinABottle** [DustinABottle/GameLauncher#2]
Frameworks for:

- [x] GUI

 

- [x] Socket communication or alternatives

- [x] Playground for games (basemodel)

**Comment by Thomath** [comment]
[ENet](http://enet.bespin.org/Features.html) - Library for sending organized UDP packages as if they were TCP packages. 

It can be used to get "big" and fast data throughput (UDP) while maintaining the ability to process them in order (TCP) by assigning those packages specific IDs.

**Comment by DustinABottle** [comment]
[Qt Creator](https://www.qt.io/download) - Framework to create powerful GUIs
* allows custom buttons and graphics
* building block concept
* good documentation

But: To use Qt with Visual Studio, a Plugin is required. This allows you to create a QtProject within Visual Studio, but i dont know if we could get into trouble later on using a QtProject instead of a regular Console Application.

**Comment by DustinABottle** [comment]
GUI -QtCreator
Sockets - Winsocket
Basemodel - OpenGL
